### ISSUE TITLE
Error in category

### ISSUE THREAD

**Issue by bipashnaaa** [prabhatbamjan/clothify#16]
Despite any sort of sorting or classification, items belonging to the three categories (kids, female, and male) are displayed all at once on the "All Products" page.
![image](https://github.com/prabhatbamjan/clothify/assets/166930981/8c8b80ad-7b27-4c0d-99d9-bad46b2189bd)

**Comment by aakrit98** [comment]
![Screenshot 2024-05-20 115814](https://github.com/prabhatbamjan/clothify/assets/119128856/58513bc8-7cc5-4fee-ba6d-d43444f679be)
The category in the ecommerce has been fixed.
